apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: elastiflow
spec:
  selector:
    app: elastiflow
  ports:
    - port: 6343
      targetPort: 6343
      protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastiflow
  labels:
    app: elastiflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastiflow
  template:
    metadata:
      labels:
        app: elastiflow
    spec:
      containers:
        - name: logstash
          image: robcowart/elastiflow-logstash-oss:3.5.0_7.0.1
          securityContext:
            privileged: true
          env:
            - name: ELASTIFLOW_DEFAULT_APPID_SRCTYPE
              value: "__UNKNOWN"
            - name: ELASTIFLOW_RESOLVE_IP2HOST
              value: "false"
            - name: ELASTIFLOW_NAMESERVER
              value: "9.9.9.9"
            - name: ELASTIFLOW_NETFLOW_IPV4_PORT
              value: "2055"
            - name: ELASTIFLOW_SFLOW_IPV4_PORT
              value: "6343"
            - name: ELASTIFLOW_IPFIX_TCP_IPV4_PORT
              value: "4739"
            - name: ELASTIFLOW_ES_HOST
              value: "http://elasticsearch:9200"
            - name: LS_JAVA_OPTS
              value: "-Xms256m -Xmx1g"
          ports:
            - containerPort: 6343
              protocol: UDP
