apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    type: kibana
    app: elasticsearch
spec:
  selector:
    type: kibana
    app: elasticsearch
  ports:
    - port: 5601
      targetPort: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: elasticsearch
    type: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      type: kibana
  template:
    metadata:
      labels:
        app: elasticsearch
        type: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:7.0.1
          env:
            - name: action.destructive_requires_name
              value: "true"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "5601"
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
            - name: KIBANA_DEFAULTAPPID
              value: "dashboard/653cf1e0-2fd2-11e7-99ed-49759aed30f5"
            - name: LOGGING_QUIET
              value: "true"
          ports:
            - containerPort: 5601
              name: http
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kibana
spec:
  to:
    kind: Service
    name: kibana
    weight: 100
  port:
    targetPort: 5601
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
